	reader_system u0 (
		.altera_up_sd_card_avalon_interface_0_avalon_sdcard_slave_chipselect  (<connected-to-altera_up_sd_card_avalon_interface_0_avalon_sdcard_slave_chipselect>),  // altera_up_sd_card_avalon_interface_0_avalon_sdcard_slave.chipselect
		.altera_up_sd_card_avalon_interface_0_avalon_sdcard_slave_address     (<connected-to-altera_up_sd_card_avalon_interface_0_avalon_sdcard_slave_address>),     //                                                         .address
		.altera_up_sd_card_avalon_interface_0_avalon_sdcard_slave_read        (<connected-to-altera_up_sd_card_avalon_interface_0_avalon_sdcard_slave_read>),        //                                                         .read
		.altera_up_sd_card_avalon_interface_0_avalon_sdcard_slave_write       (<connected-to-altera_up_sd_card_avalon_interface_0_avalon_sdcard_slave_write>),       //                                                         .write
		.altera_up_sd_card_avalon_interface_0_avalon_sdcard_slave_byteenable  (<connected-to-altera_up_sd_card_avalon_interface_0_avalon_sdcard_slave_byteenable>),  //                                                         .byteenable
		.altera_up_sd_card_avalon_interface_0_avalon_sdcard_slave_writedata   (<connected-to-altera_up_sd_card_avalon_interface_0_avalon_sdcard_slave_writedata>),   //                                                         .writedata
		.altera_up_sd_card_avalon_interface_0_avalon_sdcard_slave_readdata    (<connected-to-altera_up_sd_card_avalon_interface_0_avalon_sdcard_slave_readdata>),    //                                                         .readdata
		.altera_up_sd_card_avalon_interface_0_avalon_sdcard_slave_waitrequest (<connected-to-altera_up_sd_card_avalon_interface_0_avalon_sdcard_slave_waitrequest>), //                                                         .waitrequest
		.altera_up_sd_card_avalon_interface_0_conduit_end_b_SD_cmd            (<connected-to-altera_up_sd_card_avalon_interface_0_conduit_end_b_SD_cmd>),            //         altera_up_sd_card_avalon_interface_0_conduit_end.b_SD_cmd
		.altera_up_sd_card_avalon_interface_0_conduit_end_b_SD_dat            (<connected-to-altera_up_sd_card_avalon_interface_0_conduit_end_b_SD_dat>),            //                                                         .b_SD_dat
		.altera_up_sd_card_avalon_interface_0_conduit_end_b_SD_dat3           (<connected-to-altera_up_sd_card_avalon_interface_0_conduit_end_b_SD_dat3>),           //                                                         .b_SD_dat3
		.altera_up_sd_card_avalon_interface_0_conduit_end_o_SD_clock          (<connected-to-altera_up_sd_card_avalon_interface_0_conduit_end_o_SD_clock>),          //                                                         .o_SD_clock
		.clk_clk                                                              (<connected-to-clk_clk>),                                                              //                                                      clk.clk
		.reset_reset_n                                                        (<connected-to-reset_reset_n>),                                                        //                                                    reset.reset_n
		.sdram_controller_0_s1_address                                        (<connected-to-sdram_controller_0_s1_address>),                                        //                                    sdram_controller_0_s1.address
		.sdram_controller_0_s1_byteenable_n                                   (<connected-to-sdram_controller_0_s1_byteenable_n>),                                   //                                                         .byteenable_n
		.sdram_controller_0_s1_chipselect                                     (<connected-to-sdram_controller_0_s1_chipselect>),                                     //                                                         .chipselect
		.sdram_controller_0_s1_writedata                                      (<connected-to-sdram_controller_0_s1_writedata>),                                      //                                                         .writedata
		.sdram_controller_0_s1_read_n                                         (<connected-to-sdram_controller_0_s1_read_n>),                                         //                                                         .read_n
		.sdram_controller_0_s1_write_n                                        (<connected-to-sdram_controller_0_s1_write_n>),                                        //                                                         .write_n
		.sdram_controller_0_s1_readdata                                       (<connected-to-sdram_controller_0_s1_readdata>),                                       //                                                         .readdata
		.sdram_controller_0_s1_readdatavalid                                  (<connected-to-sdram_controller_0_s1_readdatavalid>),                                  //                                                         .readdatavalid
		.sdram_controller_0_s1_waitrequest                                    (<connected-to-sdram_controller_0_s1_waitrequest>),                                    //                                                         .waitrequest
		.sdram_controller_0_wire_addr                                         (<connected-to-sdram_controller_0_wire_addr>),                                         //                                  sdram_controller_0_wire.addr
		.sdram_controller_0_wire_ba                                           (<connected-to-sdram_controller_0_wire_ba>),                                           //                                                         .ba
		.sdram_controller_0_wire_cas_n                                        (<connected-to-sdram_controller_0_wire_cas_n>),                                        //                                                         .cas_n
		.sdram_controller_0_wire_cke                                          (<connected-to-sdram_controller_0_wire_cke>),                                          //                                                         .cke
		.sdram_controller_0_wire_cs_n                                         (<connected-to-sdram_controller_0_wire_cs_n>),                                         //                                                         .cs_n
		.sdram_controller_0_wire_dq                                           (<connected-to-sdram_controller_0_wire_dq>),                                           //                                                         .dq
		.sdram_controller_0_wire_dqm                                          (<connected-to-sdram_controller_0_wire_dqm>),                                          //                                                         .dqm
		.sdram_controller_0_wire_ras_n                                        (<connected-to-sdram_controller_0_wire_ras_n>),                                        //                                                         .ras_n
		.sdram_controller_0_wire_we_n                                         (<connected-to-sdram_controller_0_wire_we_n>),                                         //                                                         .we_n
		.sdram_controller_clock_0_clk                                         (<connected-to-sdram_controller_clock_0_clk>),                                         //                                 sdram_controller_clock_0.clk
		.sys_sdram_pll_0_sdram_clk_clk                                        (<connected-to-sys_sdram_pll_0_sdram_clk_clk>)                                         //                                sys_sdram_pll_0_sdram_clk.clk
	);

